name: R Function Trigger
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  run-r-function:
    runs-on: ubuntu-latest-4-cores
    container: ghcr.io/${{ github.repository }}/r-faasr:latest
    steps:
      - uses: actions/checkout@v3
      
      # R and packages are already installed in the container
      
      - name: Make R script executable
        run: chmod +x rscript.r
      
      - name: Run R script
        run: |
          Rscript rscript.r
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Verify execution
        run: |
          if [ $? -eq 0 ]; then
            echo "R script executed successfully"
          else
            echo "R script execution failed"
            exit 1
          fi 