name: R Function Trigger
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  run-r-function:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}/r-faasr:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install missing FaaSr package
        run: |
          echo "Installing FaaSr and dependencies..."
          Rscript -e "
          # Install FaaSr and any missing dependencies
          install.packages(c('FaaSr', 'jsonlite', 'cli', 'httr', 'glue', 'base64enc', 'paws.storage'), 
                          dependencies=TRUE, 
                          repos='https://cloud.r-project.org')
          
          # Verify installation
          library(FaaSr)
          cat('✓ FaaSr installed and loaded successfully\n')
          "
      
      - name: Verify required files exist
        run: |
          if [ ! -f "test_workflow.json" ]; then
            echo "Error: test_workflow.json not found"
            exit 1
          fi
          if [ ! -f "faasr_env" ]; then
            echo "Error: faasr_env not found"
            exit 1
          fi
          if [ ! -f "rscript.r" ]; then
            echo "Error: rscript.r not found"
            exit 1
          fi
          echo "✓ All required files found"
      
      - name: Run R script
        run: |
          Rscript rscript.r
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
